# Discord configuration
DISCORD_BOT_TOKEN = 'YOUR_DISCORD_BOT_TOKEN'
DISCORD_SERVER_ID = 'YOUR_DISCORD_SERVER_ID'
NOTIFICATION_CHANNEL_ID = 'YOUR_NOTIFICATION_CHANNEL_ID'

# YouTube configuration
YOUTUBE_API_KEY = 'YOUR_YOUTUBE_API_KEY'
YOUTUBE_CHANNEL_ID = 'YOUR_YOUTUBE_CHANNEL_ID'

# Twitch configuration
TWITCH_CLIENT_ID = 'YOUR_TWITCH_CLIENT_ID'
TWITCH_CLIENT_SECRET = 'YOUR_TWITCH_CLIENT_SECRET'
TWITCH_ACCESS_TOKEN = 'YOUR_TWITCH_ACCESS_TOKEN'
TWITCH_CHANNEL_NAME = 'YOUR_TWITCH_CHANNEL_NAME'

# Reddit configuration
REDDIT_CLIENT_ID = 'YOUR_REDDIT_CLIENT_ID'
REDDIT_CLIENT_SECRET = 'YOUR_REDDIT_CLIENT_SECRET'
REDDIT_USER_AGENT = 'YOUR_REDDIT_USER_AGENT'
SUBREDDIT_NAME = 'YOUR_SUBREDDIT_NAME'

# TikTok configuration
# If you're using web scraping, you might not need configuration here
